### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [PenguinComputing/pod#3]
hey @PenguinComputing! If you are interested, we can build images for you on [singularity hub](singularity-hub.org). The builders are still serving the (since old) 2.2, but will be updated with 2.3 when it's released!

Also, I'll be moving into development of the next version soon, which will have private endpoints for clusters. Any feedback or suggestions that you might have would be greatly appreciated to develop Singularity Hub to be useful for your group.

**Comment by victorgregoriopenguin** [comment]
@vsoch, thank you for your offer!  Yes, we are interested.  I will reach out to you offline to coordinate.
